name: Update cms/master
on:
  push:
    branches:
      - main
jobs:
  update-cms-master:
    name: Merge master into release after a PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Generate provenance
        #uses: slsa-framework/github-actions-demo@v0.1
        uses: slsa-framework/slsa-github-generator/.github/workflows/builder_nodejs_slsa3.yml@v1.6.0
        with:
          artifact_path: package.json

      - name: Upload provenance
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: build.provenance
